name: Node.js CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Verify Node Version
        run: node -v

  trigger-fireflink:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Trigger FireFlink Automation
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Channu12/Fireflink_Integration/dispatches \
            -d "{\"event_type\":\"trigger-automation\",\"client_payload\":{
              \"pr_number\":\"${{ github.event.pull_request.number }}\",
              \"pr_title\":\"${{ github.event.pull_request.title }}\",
              \"pr_branch\":\"${{ github.head_ref }}\",
              \"repo_owner\":\"${{ github.repository_owner }}\",
              \"repo_name\":\"${{ github.event.repository.name }}\",
              \"commit_sha\":\"${{ github.event.pull_request.head.sha }}\"
            }}"
