name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Verify Node Version
        run: node -v

  trigger-fireflink:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Trigger FireFlink Automation
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{
            "event_type": "trigger-automation",
            "client_payload": {
              "url": "${{ vars.FIREFLINK_URL }}",
              "token": "${{ vars.FIREFLINK_TOKEN }}",
              "username": "${{ vars.USERNAME }}",
              "projectType": "${{ vars.FIREFLINK_PROJECT_TYPE }}"
            }
          }'
